fivetran:
    target: prod
    outputs:
      prod:
        type: databricks
        host: "servicenow.nopnop.pro"
        port: 80
        http_path: "sql/1.0/warehouses/25dd6c306358837d"
        token: "dapi030549dc5c54f293absd23232323"
        schema: "PUBLIC"
        connect_timeout: 60
        connect_retries: 5
        threads: 1
        connection_parameters:
          staging_allowed_local_path: "/proc/self"
